

spring:
  dataSource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/springbook?serverTimezone=UTC
    username: root
    password: root
#    hikari:
#      auto-commit: false

# ref : https://n1tjrgns.tistory.com/172
  main:
    allow-bean-definition-overriding: true